### ISSUE TITLE
Citus

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2675]
### Problem

The current single node Postgres DB will not perpetually scale for large DB and prolonged high TPS scenarios.
Eventually the mirror node ingestion and read times will be impacted.

### Solution

Adopt a multi node distributed approach that utilizes distribution of data and queries. After a successful POC, CitusDB offers an applicable solution.

```[tasklist]
### Documentation
```

```[tasklist]
### Schema
- [x] #2456
- [x] #2713
- [x] #2726
- [x] #2679
- [x] #2680
- [x] #2681
- [x] #2682
- [x] #4797
- [ ] #2683
- [x] #2646
- [ ] #4814
- [ ] #4963
- [x] #5169
- [ ] #5359
- [ ] #5409
- [ ] #5769
- [ ] #6369
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6449
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6448
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7671
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7668
```

```[tasklist]
### Importer
- [x] #3810
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7007
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7562
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7571
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7669
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7663
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7672
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7673
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7668
```

```[tasklist]
### REST
- [x] #2676
- [x] #4654
- [ ] #4655
- [x] #5224
- [x] #5225
- [x] #5226
- [x] #5227
- [x] #5228
- [x] #5231
- [ ] #5232
- [ ] #5235
- [x] #5236
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6936
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6938
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6937
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6939
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6935
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6933
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6976
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6977
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7042
```

```[tasklist]
### Rosetta
- [ ] #4912
```

```[tasklist]
### Deployment
- [x] #2684
- [x] #2688
- [x] #2725
- [x] #4972
- [x] #5043
- [x] #5151
- [ ] #5306
- [ ] #5233
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5750
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5622
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6931
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6887
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6972
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7613
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7619
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8125
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8188
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8189
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8604
```

```[tasklist]
### Performance
- [ ] #2685
- [ ] #2686
- [x] #2769
```

Ref
[Citus POC](https://github.com/hashgraph/hedera-mirror-node/compare/citus-poc?expand=1)

### Alternatives

Too many to list

**Comment by steven-sheehy** [comment]
Closing as most tasks are completed. Another epic for list queries has been extracted from this: https://github.com/hashgraph/hedera-mirror-node/issues/5409
