### ISSUE TITLE
Release checklist 0.45

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#2879]
### Problem

We need a checklist to verify the release is rolled out successfully.

## Preparation
- [x] PRs and issues that are merged/closed have milestone populated
- [x] PRs and issues targeting release are merged, closed, or re-targeted
- [x] GitHub checks for branch are passing
- [x] Automated Kubernetes deployment successful
- [x] Tag release
- [x] Upload release artifacts
- [x] Publish release
## Integration
- [x] Deploy to VM
- [x] Deploy Rosetta API
- [x] Rosetta tests
## Performance
- [x] Deploy to Kubernetes
- [x] Deploy to VM
- [x] gRPC API performance tests
- [x] Importer performance tests
- [x] REST API performance tests
- [x] Migrations tested against mainnet clone
## Previewnet
- [x] Deploy to VM
- [x] Deploy Rosetta API
- [x] Rosetta tests
## Testnet
- [x] Deploy to VM
- [x] Deploy Rosetta API
- [x] Rosetta tests
## Mainnet
- [x] Deploy to Kubernetes EU
- [x] Deploy to Kubernetes NA
- [x] Deploy to VM
- [x] Rosetta tests

**Comment by steven-sheehy** [comment]
All tasks completed.
