### ISSUE TITLE
Release checklist 0.50

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3272]
### Problem

We need a checklist to verify the release is rolled out successfully.

## Preparation
- [x] Milestone field populated on [relevant issues](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aclosed+no%3Amilestone+sort%3Aupdated-desc)
- [x] Nothing [open](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aopen+sort%3Aupdated-desc+milestone%3A0.51.0) for milestone
- [x] GitHub checks for branch are passing
- [x] Automated Kubernetes deployment successful
- [x] Tag release
- [x] Upload release artifacts
- [x] Publish release
## Integration
- [x] Deploy to VM
- [x] Rosetta tests
## Performance
- [x] Deploy to Kubernetes
- [x] Deploy to VM
- [x] gRPC API performance tests
- [x] Importer performance tests
- [x] REST API performance tests
- [x] Migrations tested against mainnet clone
- [x] Rosetta tests
## Previewnet
- [x] Deploy to VM
## Testnet
- [x] Deploy to VM
- [x] Rosetta tests
## Mainnet
- [x] Deploy to Kubernetes EU
- [x] Deploy to Kubernetes NA
- [x] Deploy to VM
- [x] Rosetta tests
