### ISSUE TITLE
Release checklist 0.59

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3981]
### Problem

We need a checklist to verify the release is rolled out successfully.

## Preparation
- [x] Milestone field populated on [relevant issues](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aclosed+no%3Amilestone+sort%3Aupdated-desc)
- [x] Nothing [open](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aopen+sort%3Aupdated-desc+milestone%3A0.59.0) for milestone
- [x] GitHub checks for branch are passing
- [x] Automated Kubernetes deployment successful
- [x] Tag release
- [x] Upload release artifacts
- [x] Publish release
## Integration
- [x] Deploy to VM
## Performance
- [x] Deploy to Kubernetes
- [x] Deploy to VM
- [ ] gRPC API performance tests
- [ ] Importer performance tests
- [ ] REST API performance tests
- [ ] Migrations tested against mainnet clone
## Previewnet
- [ ] Deploy to VM
## Staging
- [ ] Deploy to Kubernetes EU
- [ ] Deploy to Kubernetes NA
## Testnet
- [ ] Deploy to VM
## Mainnet
- [ ] Deploy to Kubernetes EU
- [ ] Deploy to Kubernetes NA
- [ ] Deploy to VM
- [ ] Deploy to ETL
