### ISSUE TITLE
Show NFT transfers on transactions list API

### ISSUE THREAD

**Issue by mohsin-hedera** [hashgraph/hedera-mirror-node#4099]
### Problem

If there is an atomic swap between an NFT and HBAR, the transaction ID shows all the relative details on Mirror Node just fine. However, if I go check the accountID generic info about transactions that have taken place, it does not get mapped. As if that never happened. So one of the consequence is that on Hashpack wallet for example,  in the transaction history it cannot be found either.

We have 2 nft transactions here
https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.34754823-1657300036-20338410
https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.1856648-1657300025-266773509
as you can see, the wallet 0.0.47548259 is part of them both, but then if you look here
https://testnet.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.47548259
there is NO TRACE AT ALL about those nft transfers!!!

From @xin-hedera 

> This is expected response from the accounts rest api endpoints or the transactions endpoint with the account.id filter. We chose not to show such transactions if the account is only involved in nft transfers for performance concern. With recent optimizations, it’s probably time for us to reevaluate the performance impact and make improvident there.

### Solution

```[tasklist]
### Tasks
- [ ] #6008
- [ ] #6009
- [ ] #6010
- [ ] #6011
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6028
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6126
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6112
```

**Comment by robkainz** [comment]
Same problem with Wallawallet. Though we now display NFT transactions for NFT transfers for a specific serial number in our upcoming release, there is no simple way for a user to correlate the "Crypto Transfer" transactions that show up in the user's account with the NFT transfer transactions. This will certainly increase support queries when people begin asking questions about transactions that they don't remember performing in order to pay network/node fees for transferring NFTs. We need it to provide an accurate picture of an NFT transfer transaction that otherwise shows up as a crypto transfer (with no mention of the NFT that was moved.)

**Comment by shierve** [comment]
I have encountered this issue too. For some extra information, [in this design doc](https://github.com/hashgraph/hedera-mirror-node/blob/main/docs/design/nft.md) it is mentioned that nft_transfers is only implemented for calling /transactions with a specific id, but not when querying for a list, so it is indeed an intended response. It would be interesting for many nft use cases if it was changed, or maybe include a flag to set nft_transfers to true, and leaving the default call without nft_transfers for performance concerns.

**Comment by steven-sheehy** [comment]
Thanks all for your feedback. We've prioritized it for this sprint with it planned for completion by 0.83.

**Comment by topshef** [comment]
@xin-hedera i think the following is expected behaviour as you mentioned above, but is there any plan or open issue to allow account filter to pick up NFT-only transactions? Example:

Account 0.0.25200 is the NFT sender here ...
https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?timestamp=eq:1733010378.153975190

but if filtering for this account the transaction is not returned..
https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?timestamp=eq:1733010378.153975190&account.id=0.0.25200
