### ISSUE TITLE
Google Cloud Marketplace

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#518]
**Problem**
We should enable users to run the Hedera Mirror Node in [Google Cloud Marketplace](https://console.cloud.google.com/marketplace) with just a few clicks

**Solution**
- Depends on requester pay buckets (#357) being complete and available
- Depends on any outstanding Kubernetes tasks that are critical (TBD)

**Alternatives**

**Additional Context**

**Comment by steven-sheehy** [comment]
Please fill in details of what this ticket is for. The issue templates are there for a reason.

**Comment by steven-sheehy** [comment]
## Marketplace Requirements

May break these into sub-tasks later if appropriate.

- [ ] Become a Google Cloud Marketplace [vendor](https://docs.google.com/forms/d/e/1FAIpQLSdW1ydFzsS3iw85pPpvgVSIcmGErx1FSiuQW7rMi8cCG1BhYg/viewform)
- [ ] Complete the [Project Info form](https://docs.google.com/forms/d/e/1FAIpQLSfddn4mwKnqtLNQ-m7IgRZ-bgTz4BOsrEDWCf3XBjc_ogKNnA/viewform)
- [ ] Review and complete the [open source compliance requirements](https://cloud.google.com/marketplace/docs/partners/open-source-compliance)
- [x] Create a public Git repository for your app's configuration, user guide, and other resources to run your app
- [ ] [Setup your Google Cloud Environment](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/set-up-environment)
  - [x] Create a Google project
  - [x] Set up a container registry
  - [x] Enable the Container Analysis API
  - [ ] Add your solution in Partner Portal
  - [ ] Create a development cluster in Kubernetes Engine
  - [ ] Install the mpdev development tool
  - [x] Organizing your releases: semver
  - [ ] Choose your product identifiers
- [x] Choose a pricing model: free
- [ ] [Create your app package](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package)
  - [x] Contain a LICENSE file
  - [x] Helm chart
    - [x] Use only beta or generally available Kubernetes resources
    - [ ] Install an [Application](https://github.com/kubernetes-sigs/application) custom resource
    - [ ] Allow parameter substitution for:
      - [ ] Namespace
      - [ ] App name
      - [ ] Container images
      - [ ] License secret
    - [ ] Client side templating deployment
  - [ ] Anthos support
    - [x] PVC not hardcoded to a specific StorageClass
    - [ ] Ingress conditionally enabled based upon `x-google-marketplace INGRESS_AVAILABLE`
    - [x] Don't use `default` service account
    - [ ] Populate `x-google-marketplace SERVICE_ACCOUNT` with app service accounts
  - [x] Istio Support: N/A
  - [x] Commercial billing agent: N/A
  - [ ] [Helm Deployer image](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md)
    - [ ] Folder structure
    - [ ] schema.yaml
    - [ ] Dockerfile
    - [ ] Automate image building
  - [ ] App images
    - [ ] Your app's main image must be in the root of the repository: We don't have a main image, they're all in sub-folders
    - [ ] Deployer pushed to `gcr.io/exampleproject/exampleapp/deployer`
    - [x] If your app uses additional container images, each additional image must be in its own folder under the main image
    - [x] All of your app's images must be tagged with the release track and the current version
  - [ ] [Verification process](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/verification-integration.md)
    - [ ] Test data folder
    - [ ] Test schema
    - [ ] Integration test pod
    - [ ] Test pod annotated with `marketplace.cloud.google.com/verification:test` or `helm.sh/hook:test-success`
    - [ ] Run verification locally using mpdev
  - [ ] User guide
    - [ ] Overview section
    - [ ] Setup / Requirements
    - [ ] Installation
    - [ ] Basic usage
    - [ ] Backup and Restore
    - [ ] Updates
    - [ ] Scaling
    - [ ] Uninstallation
- [ ] [Submit the app to Google Cloud Marketplace](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/submitting)
  - [ ] Upload your images
  - [ ] Add your solution in Partner Portal
  - [ ] Getting Google Cloud Marketplace approval
- [ ] [Maintaining the application](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/maintaining-solution)

**Comment by steven-sheehy** [comment]
Completed with 0.13.5
