### ISSUE TITLE
HIP-584: Enhance `eth_call` with token precompile logic

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5297]
### Problem

We need to enhance `eth_call` to support token precompile calls.

### Solution

Implement:

- [x] #4502
- [x] #5300 
- [x] #5301
- [x] #5302
- [x] #5620 
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/5399
- [x] https://github.com/hashgraph/hedera-mirror-node/pull/5721
- [x] https://github.com/hashgraph/hedera-mirror-node/pull/5602
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/5584
- [x] https://github.com/hashgraph/hedera-mirror-node/pull/5762
