### ISSUE TITLE
HIP-584: `eth_estimateGas` without precompiles

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node#5500]
### Problem

We need to add support for `eth_estimateGas` without precompiles.

### Solution

The following tasks have been defined:

- [x] https://github.com/hashgraph/hedera-mirror-node/issues/5497
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/5498
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/5499
- [x] #5900 
- [x] #4007 
- [x] #4646 
- [x] #5946 
- [x] #5987
- [x] #5951 
- [x] #5960 
- [x] #6029 
- [x] #6052
- [x] #6053
- [x] #6054
- [x] #6068 
- [x] #5596 
- [x] #6076
- [x] #6077
