### ISSUE TITLE
Release Checklist 0.76

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5535]
### Problem

We need a checklist to verify the release is rolled out successfully.

## Preparation

- [x] Milestone field populated on
  relevant [issues](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aclosed+no%3Amilestone+sort%3Aupdated-desc)
- [x] Nothing open
  for [milestone](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aopen+sort%3Aupdated-desc+milestone%3A0.76.0)
- [x] GitHub checks for branch are passing
- [x] Automated Kubernetes deployment successful
- [x] Tag release
- [x] Upload release artifacts
- [ ] Manual Submission for GCP Marketplace verification by google
- [ ] Publish marketplace release
- [x] Publish release

## Performance

- [x] Deployed
- [x] gRPC API performance tests
- [x] Importer performance tests
- [x] REST API performance tests

## Previewnet

- [x] Deployed

## Staging

- [x] Deployed

## Testnet

- [x] Deployed

## Mainnet

- [x] Deployed to Kubernetes EU
- [x] Deployed to Kubernetes NA
- [x] Deployed to VM
