### ISSUE TITLE
Bucket restructure

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#5605]
### Problem

Currently consensus nodes write stream files to node account id based paths.We propose changing the current stream data bucket folder structure from node account ID based to node ID based. Additionally, we propose incorporating shard into the path to be future compatible with sharding when it's enabled. We are also proposing a rollup mechanism to reduce cloud storage duplication and improve historical sync times of mirror nodes.

### Solution

The solution for this is listed in the listed [HIP-679](https://github.com/mgoelswirlds/hedera-improvement-proposal/blob/main/HIP/hip-679.md).

```[tasklist]
### Tasks
- [ ] #4388
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5713
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5759
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6023
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6024
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6025
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6079
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7050
```

**Comment by steven-sheehy** [comment]
Closing since HIP-679 won't be implemented in favor of block nodes.
