### ISSUE TITLE
Store all entity changes

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6110]
### Problem

As a user of the Hedera network, I'd like the ability to know the exact state of my entities (accounts, contracts, tokens, etc) at any point in time.

### Solution

Add a history table to every entity-related table that does not currently have one. For any field that updates more often than CRUD updates, capture those separately.

```[tasklist]
### Tasks
- [ ] #6111
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6112
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6113
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5274
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/3576
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5775
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6074
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5196
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6301
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/321
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6304
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6114
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6283
- [ ] node stake history
- [ ] network stake history
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/432
```

**Comment by steven-sheehy** [comment]
Closing this since all tasks that are related to persistence are completed. There's a couple API only tasks that are not technically related to "store all entity changes" and can be worked on separately.
