### ISSUE TITLE
HIP-584: Implement GrantKycPrecompile, RevokeKycPrecompile and WipePrecompile

### ISSUE THREAD

**Issue by agadzhalov** [hashgraph/hedera-mirror-node#6321]
This work package would enhance the user experience by extending eth_estimateGas support with more precompiles. Those are `GrantKycPrecompile`, `RevokeKycPrecompile` and `WipePrecompile` .

**Implementation of Logic**
1. Copy `GrantKycLogic`, `RevokeKycLogic`, `WipeLogic` from `hedera-services` to `hedera-mirror-web3`
2. Integrate them with the `Store` interface
3. Add `javadoc` describing what has changed and how we integrated it in the `mirror-node`’s code base

**Implementation of Precompile**

4. Copy `GrantKycPrecompile` , `RevokeKycPrecompile` , `WipePrecompile` from `hedera-services` to `hedera-mirror-web3`.
5. Integrate them with the `Store` interface
6. Add `javadoc` describing what has changed and how we integrated it in the mirror-node’s code base

**Testing**

- Create integration tests in `ContractCallServicePrecompileTest` in `hedera-mirror-web3` and validate that the return gas estimates in the desired range with offset between 5% and 20% more than the actual gas used
- Create acceptance tests in `PrecompileContractFeature` in `hedera-mirror-test` and validate that the return gas estimates in the desired range with offset between 5% and 20% more than the actual gas used
- Make these `3 precompiles` work end to end using the `Store` abstraction that internally uses in-memory stacked frame state design and return proper gas estimates

- [x] hashgraph/hedera-mirror-node#6335
- [x] hashgraph/hedera-mirror-node#6333
- [x] hashgraph/hedera-mirror-node#6323
- [x] hashgraph/hedera-mirror-node#6334
- [x] hashgraph/hedera-mirror-node#5659
- [x] hashgraph/hedera-mirror-node#6299
- [x] hashgraph/hedera-mirror-node#5656

**Acceptance tests**
- [x] #5683 
- [ ] #5685

**Comment by steven-sheehy** [comment]
All sub-tasks complete except one which is also tracked by another epic.
