### ISSUE TITLE
Entity Transaction

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#6520]
### Problem

As a mirrornode user, I'd like to search an entity's transactions. Currently `/api/v1/accounts/{id}` and `/api/v1/transactions?account.id=X` can search transactions for an account / contract with some limitations.

### Solution

- Add an `EntityTransaction` domain class with entity id, transaction consensus timestamp, and other frequently used transaction info, creates objects for each entity a transaction involves, and persists the objects to database
- Extend the transactions REST API with `entity.id` query parameter to support searching transactions of a specific entity id

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6521
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6522
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/5274
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7232
```

**Comment by steven-sheehy** [comment]
Closing as we don't think this is the correct approach.
