### ISSUE TITLE
HIP-584: Inspect `api/v1/contracts/call` performance via `K6` tests and `Grafana`

### ISSUE THREAD

**Issue by agadzhalov** [hashgraph/hedera-mirror-node#6609]
This work package would help us gather metrics for `eth_call` and `eth_estimateGas` execution and point potential performance problems.

### **Motivation**

Ongoing support of `eth_call` and `eth_estimateGas` executions would increase the number of users that start using these new functionalities. Eventually this would increase the number of requests against the Archive Node and performance issues might be faced. This package would aim to reduce the performance bottlenecks.

### **Tools we are going to use**

 - **Grafana** -  app for visualising data. Allows us to build charts, graphs and dashboards of data we want to visualise
 - **Prometheus** - data source. Collects all metrics about the app in one centralized place where the metrics are being changed every second. Grafana visualise metrics based on Prometheus.
 - **k6** - an open-source load testing tool for testing the performance of APIs, microservices, and websites. Tests are written in javascript
 
### **Implementation Plan**

Write `k6` test scenarios for the most heavy-loaded operations.

- [x] Write `k6` test for `CREATE_FUNGIBLE_TOKEN_WITH_CUSTOM_FEES` (actual gas: `23134640`) @kselveliev 
- [x] Write `k6` test for `CREATE_NFT_WITH_CUSTOM_FEES` (actual gas: `23133124`) @dikel 
- [x] Write `k6` test for `CREATE_FUNGIBLE_TOKEN` (actual gas: `11590398`)
- [x] Write `k6` test for `CREATE_NFT` (actual gas: `11574020`)
- [x] Write `k6` test for `DISSOCIATE_AND_ASSOCIATE` (actual gas: `1434814`)

Inspect the system behaviour via `Prometheus` and `Grafana` and observe that these specific aspects are run successfully:
 
 - [x] `DB query responses`
 - [x] `Number of execution of DB queries`
 - [x] `Response times`
 - [x] `Number of requests per second`
 
 Perform performance improvements:

- [ ] `Lazy loading` approach (e.g. load only the needed specific data (e.g. `token name`) of a given model like token, instead of the whole data/model)

**Comment by steven-sheehy** [comment]
We should figure out a way to reuse the solidity code between the web3 and k6 test modules, if possible. This can potentially be a separate task, but let's keep it mind with anything we develop to reuse as much as possible.
