### ISSUE TITLE
Sunsetting account balance file

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6623]
### Problem

Once consensus nodes start persisting accounts to disk, they may stop generating account balance files due to the increased number of accounts this enables.

### Solution

* Analyze places that use `account_balance`, `account_balance_file` and `token_balance`
* Generate historical `account_balance` and `token_balance` entries from record file data
* Deduplicate historical balance info
* Provide different balance granularity depending upon timestamp so that times closer to now have more frequent balance snapshots
* Research bootstrapping entity balance

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6677
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6678
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6679
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6680
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6681
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6682
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6683
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6700
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6701
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/3507
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6884
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7005
```
