### ISSUE TITLE
HIP-584 Historical: add queries/unions and Stores support for historical data retrieval

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-mirror-node#6697]
# Overview of Package

### Definition

We need to add support of historical blocks related to the work defined in HIP-584, so that we enrich user experience.

### **Abstract**

This work package would enhance the user experience by extending `eth_call` to work with different block values.

### **Motivation**

Ongoing support of `eth_call` executions requires that we accept different values for the block argument. Currently we support only `“latest”` and with this package we want to extend the support to include a block number specified in a hexadecimal format or with string values - `“latest”` or `“earliest”`.

### **Rationale**

As defined in HIP-415, in Hedera the block number is the consecutive number of a record file that was streamed from the consensus nodes. 

The JSON-RPC endpoint `eth_call` accepts a block number as an input argument. This block number specifies that the execution of `eth_call` has to be based on the state that is produced after the execution of all transactions into the specified block. In this way, the state would reliably reflect the changes included in the given block.

The block number can be specified in a hexadecimal format or with string values - `“latest”` or `“earliest”`.  The other strings defined in Ethereum won’t be supported, since they don’t have an alternative in Hedera. These are - `“pending”`, `“safe”` and `“finalized”`. In order to be possible to query historical blocks, we should meet some requirements:

### User stories

1. As a user, I want to perform `eth_call` Ethereum JSON-RPC queries using historical blocks, calling a view function of a smart contract that **does not** in turn make calls to Hedera system contracts. This will allow me to see what a particular smart contract state was in the past which I can use to develop block explorers, analytical tools, etc.

### **Specification**

1. Extend needed DB queries to filter by timestamp, defaulting to current timestamp. For the scope of this package we need to have working queries that are related to non system contract state, e.g. contract state changes, account’s balance. For the queries related to other state information we would have additional package.
For some of the tables we have a `normal` and a `historical` table, that we would to query via `UNION_ALL` statement, `sort` by timestamp and `limit` to 1. In this way we would find the correct historical information.
For other type of information like historical `account balances`, we don’t have a directly calculated value, so we would have to calculate it manually. More details are available in the design doc below.
2. Adapt `Store` to work with timestamp filters, that are propagated to the DB queries. Extend all accessor types (RW/RO CachingStateFrame accessors, DB accessors) to work with additional timestamp argument in their `get()` method

### **Backwards compatibility**

We extend the functionality of the existing code base in `hedera-mirror-web3`, so no implications here. 

### **Security Implications**

This work package shares the same security consideration like `HIP-584` itself. We may receive a bunch of requests that put high load on the network, but we have a global rate limit mechanism over the `web3` module, so we don’t have security implications specific for this work package.

### **References/Dependencies**

1. https://hips.hedera.com/hip/hip-584
2. https://hips.hedera.com/hip/hip-415
3. [Mirror-Node historical information support](https://www.notion.so/Mirror-Node-historical-information-support-70f9e448999f4f25b19b667fd72de6f1?pvs=21)
4. [EVM Archive Node with Historical block support for `eth_call` -design doc- [shared]](https://www.notion.so/EVM-Archive-Node-with-Historical-block-support-for-eth_call-design-doc-shared-7ffd952a53ff4677ac71fad1b46c9678?pvs=21)

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6895
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6812
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6813
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6969
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6970
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6971
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6856
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6958
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7036
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7037
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7034
- [ ] https://github.com/hashgraph/hedera-mirror-node/pull/7041
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7045
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7092
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7114
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7122
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7123
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7147
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7043
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7113
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7184
```
