### ISSUE TITLE
HIP-584: Extend needed DB queries to filter by timestamp

### ISSUE THREAD

**Issue by mustafauzunn** [hashgraph/hedera-mirror-node#6812]
Extend needed DB queries to filter by timestamp, defaulting to current timestamp. For the scope of this package we need to have working queries that are related to non system contract state, e.g. contract state changes, account’s balance.
For some of the tables we have a normal and a historical table, that we would to query via UNION_ALL statement, sort by timestamp and limit to 1. In this way we would find the correct historical information.
For other type of information like historical account balances, we don’t have a directly calculated value, so we would have to calculate it manually. More details are available in the design doc.

**Comment by kselveliev** [comment]
### **Implementation Plan**

- [ ] Extend DB queries for token_balance, token_transfer and token to work with timestamp filter 
- [ ] Extend DB queries for account_balance, crypto_transfer and entity to work with timestamp filter

**Comment by kselveliev** [comment]
### **Implementation Plan**

- [ ] Create new DB query for fetching historical contract state data in **ContractStateRepository**
