### ISSUE TITLE
Release Checklist 0.96

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7479]
### Problem

We need a checklist to verify the release is rolled out successfully.

## Preparation

- [ ] Milestone field populated on relevant [issues](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aclosed+no%3Amilestone+sort%3Aupdated-desc)
- [ ] Nothing open for [milestone](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aopen+sort%3Aupdated-desc+milestone%3A0.95.0)
- [ ] GitHub checks for branch are passing
- [ ] No pre-release or snapshot dependencies present in build files
- [ ] Automated Kubernetes deployment successful
- [ ] Tag release
- [ ] Publish marketplace release
- [ ] Publish release

## Performance

- [x] Deployed
- [ ] gRPC API performance tests
- [ ] Importer performance tests
- [ ] REST API performance tests

## Previewnet

- [x] Deployed

## Staging

- [ ] Deployed

## Testnet

- [ ] Deployed

## Mainnet

- [ ] Deployed
