### ISSUE TITLE
HIP-857: NFT allowance APIs

### ISSUE THREAD

**Issue by mgoelswirlds** [hashgraph/hedera-mirror-node#7480]
### Problem

Customers have requested a number of NFT allowance APIs and that are being review by the HIP Process.

### Solution

- The proposed endpoints in the HIP are designed to solve the above mentioned issue.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/4348
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7143
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/4346
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/3245
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7343
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/7498
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7499
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7500
- [x] https://github.com/hashgraph/hedera-mirror-node/issues/7690
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7760
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7858
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7859
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7874
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7937
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7938
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7982
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8078
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8176
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8185
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8255
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8270
```
