### ISSUE TITLE
Direct calls to Ethereum Precompiles

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-mirror-node#7568]
## Definition

As part of the effort to achieve full Ethereum equivalence, we need to provide a proper way for developers to call the addresses directly. Some of the more used are:

- 0x01 - ecRecover
- 0x02 - SHA2-256 hash function

More info can be found in [**[evm.codes](https://www.evm.codes/precompiled)**](https://www.evm.codes/precompiled)

## Code Changes Overview

Changes needed in the mirror-node are:

1. In [MirrorEvmTxProcessorImpl.java](https://github.com/hashgraph/hedera-mirror-node/blob/663a8b56b7d9fa97c52636b5190d8cc07c5dd3da/hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java) in method [buildInitialFrame](https://github.com/hashgraph/hedera-mirror-node/blob/663a8b56b7d9fa97c52636b5190d8cc07c5dd3da/hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java#L110), change* the check from:

```java
if (code == null && value <= 0 && !payload.isEmpty()) {
                throw new MirrorEvmTransactionException(
                        ResponseCodeEnum.INVALID_TRANSACTION, StringUtils.EMPTY, StringUtils.EMPTY);
            }
```

to: 

```java
if (code == null && value <= 0 && !payload.isEmpty() && (resolvedEvm != accounts(0x1 - 0x9))) {
                throw new MirrorEvmTransactionException(
                        ResponseCodeEnum.INVALID_TRANSACTION, StringUtils.EMPTY, StringUtils.EMPTY);
            }
```

*Given example is pseudo code, just to illustrate the needed change

## Abstract

Precompile contracts are a special kind of contracts that are bundled with the EVM at fixed addresses, and can be called with a determined gas cost. The addresses start from 1, and increment for each contract. In Hedera they are currently restricted from calling due to validation checks.

## Motivation

Allowing direct calls to the EVM Precompiles will bring Hedera one step closer to achieving EVM equivalence. 

## Behavioral Changes Overview

1. Scenario: `EOA` -call→ `Caller` (contract) -call→ `Receiver`, where `Receiver` is address between 0x1 → 0x9
    
    Before needed code changes the transaction is reverted with an `INVALID_TRANSACTION`
    
    After needed code changes the internal call succeeds and performs the corresponding operation returning the expected result
    

## Rationale

We need to behavior between the different components as well as the EVM itself. Users will expect to be able to make calls to Ethereum addresses 0x1 → 0x9. With EVM version 0.46 this is possible in the consensus node, therefore after bringing this version to the mirror node we need to make sure that this is the case as well for static calls. 

## Testing

Minimal scenarios that should be covered in the mirror-node are:

- Calling each of the precompile addresses with **correct** input should result in correct output.
- Calling each of the precompile addresses with **incorrect** input should result in revert.
- Estimate gas each of the precompile addresses with the **correct** input should result in gas estimation.
- Estimate gas each of the precompile addresses with the **incorrect** input should result in revert reason.

Minimal scenarios that should be covered in the relay/smart-contracts repo are:

- Static call towards mirror-node each of the precompile addresses with correct input should result in correct output.
- Call towards consensus node each of the precompile addresses with correct input should result in correct output.
- Estimate gas each of the precompile addresses with the **correct** input should result in gas estimation.
- Estimate gas each of the precompile addresses with the **incorrect** input should result in revert reason.

## Backwards Compatibility

No backward compatibility issues should be expected.

## Security Implications

None

## References & Dependencies

https://github.com/hashgraph/hedera-mirror-node/issues/7560 Adding the EVM v046 in `hedera-mirror-web3`
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7608
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7609
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/647
```

**Comment by bibitibooo1** [comment]
To have a test plan and then prioritise.
