### ISSUE TITLE
HIP-646/657/765: Token metadata

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7596]
### Problem

[HIP 647 Fungible Token Metadata](https://hips.hedera.com/hip/hip-646), [HIP-657 Mutable NFT Metadata](https://hips.hedera.com/hip/hip-657), and [HIP-765 NFT Collection Token Metadata Field](https://hips.hedera.com/hip/hip-765) are scheduled to be delivered in HAPI v0.48.0 as a [single](https://github.com/hashgraph/hedera-protobufs/pull/313/files) unit since they're all related. Mirror node needs to design and implement support for them.

Building on [HIP-17 Non-Fungible Tokens](https://hips.hedera.com/hip/hip-17), which, among other things, introduced the immutable `metadata` field for unique NFTs, the three new HIPs allow for metadata to be associated with both FTs and NFT collections (token class), as well as makes all metadata mutable by the introduction of the metadata key.

See also [services epic issue](https://github.com/hashgraph/hedera-services/issues/10931) and [protobuf changes PR](https://github.com/hashgraph/hedera-protobufs/pull/313).

### Solution

* Research the HIPs and how they impact mirror node
* Update the HIPs to add any REST API changes
* Create sub-tasks

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6548
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6549
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/6551
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/7765
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8075
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8318
```
