### ISSUE TITLE
HIP-874: Get topic REST API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#7925]
### Problem

[HIP-874](https://hips.hedera.com/hip/hip-874) requests the addition of a new `/api/v1/topics/{id}` REST API.

### Solution

```[tasklist]
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/774
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8283
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8284
```
