### ISSUE TITLE
Refactor and reorganize integration tests in `hedera-mirror-web3` module

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#8057]
### Problem

Currently all integrations tests in `hedera-mirorr-web3` rely on a DB test setup, which is processed in `ContractCallTestSetup`, which creates a strong dependency between all test data. As a result if we change the ID of a single entity, for example, we might break an existing set of tests or see unexpected results. In addition maintenance and adding new tests with new test data would become harder and harder in the future.

### Solution

Remove `ContractCallTestSetup` as a central database setup and refactor all integration tests to include their own test data and be self-sufficient without relying on an external setup. Each test should create their own entities and needed data, that would be discarded after the test execution.

Some extraction of ContractCallTestSetup logic into the separate integration tests, might be an option, but probably the best approach would be adding new DB test data for each separate test from scratch. Avoid extracting common entities and methods in a parent class, as eventually we would construct the same problem of a common big and complex class with DB setup.

We should rely on the existing DomainBuilder as much as possible and avoid hardcoding fields of the built entity if possible. We should use dynamic data and validate the test against it.

Also, research about [web3j-solidity-gradle-plugin](https://github.com/hyperledger/web3j-solidity-gradle-plugin) and [web3j-gradle-plugin](https://github.com/hyperledger/web3j-gradle-plugin) plugins and investigate if we can make a use of them in the refactor of web3 module integration tests

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8466
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8467
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8449
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8450
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8380
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8455
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8456
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8451
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8452
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8453
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8379
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8942
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8944
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8945
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8956
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9071
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9072
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9073
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9074
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8383
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9109
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9135
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9162
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9168
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9184
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9222
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9108
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9271
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/9317
```

**Comment by steven-sheehy** [comment]
All tasks complete
