### ISSUE TITLE
Rosetta API implementation

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#810]
**Problem**
In order to work with Rosetta, Hedera needs to implement the [Rosetta Blockchain Standard](https://github.com/coinbase/rosetta-specifications). Rosetta is an open API for integrating with exchanges and we would like to implement it to allow more exchanges to integrate with Hedera.

**Solution**
- [ ] Create a Rosetta API implementation design document in `docs/design/rosetta.md` - #1512
- ~Research [code generation](https://www.baeldung.com/spring-boot-rest-client-swagger-codegen) via provided OpenAPI specification~
- ~Prefer Java with Spring MVC to allow code reuse of domain/repository~
- [ ] Outline the high level flow from controller to service to repository - #1517
- [ ] Outline the APIs and how they map to our domain - #1517
- [ ] Outline testing approach (research automated openapi testing) - #1517
- [ ] Discuss deployment patterns  - #1512
- [ ] Utilizing `github.com/hashgraph/hedera-sdk-go` instead of `github.com/limechain/hedera-sdk-go` - #1521
- [ ] Utilizing `hedera-mirror-node` instead of LimeChain’s forked `hedera-mirror-node` in "all in one" DOckerfile - #1512
- [ ] Updating db calls with any post V1.31 db schema changes - #1515
- [ ] Update to `operations.md` and `docs/design/rosetta.md` with more documentation - #1517
- [ ] Adding a helm chart - #1513
- [ ] Add go to license regex - #1514
- [ ] Update copy rights with go file coverage - #1514
- [ ] Add a maven plugin to support build and test as part of multi module flow - #1523

**Alternatives**

**Additional Context**
