### ISSUE TITLE
Refactor `ConstractCallServicePrecompile`, `ConstractCallService` and `ContractCallSystemPrecompile`

### ISSUE THREAD

**Issue by petreze** [hashgraph/hedera-mirror-node#8381]
As the description of the WP suggests, refactor the mentioned integration tests in web3 module (`ConstractCallServicePrecompileTest`, `ConstractCallServiceTest` and `ContractCallSystemPrecompileTest`) in a way to be self-sufficient enough and rely only on the provided data in this specific test. Essentially, if some of the data in separate tests inside the same integration test file is repeated, it could abstracted away in the integration test class, if appropriate
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8451
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8452
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/8453
```
