### ISSUE TITLE
Release Checklist 0.106

### ISSUE THREAD

**Issue by jascks** [hashgraph/hedera-mirror-node#8386]
### Problem

This checklist verifies a release is rolled out successfully.

## Release Checklist

This checklist verifies a release is rolled out successfully.

## Preparation

- [x] Milestone created
- [x] Milestone field populated on
      relevant [issues](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aclosed+no%3Amilestone+sort%3Aupdated-desc)
- [x] Nothing open
      for [milestone](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aopen+sort%3Aupdated-desc+milestone%3A0.105.0)
- [x] GitHub checks for branch are passing
- [x] No pre-release or snapshot dependencies present in build files
- [ ] Verify hedera-services protobuf dependency doesn't contain any unsupported fields
- [x] Automated Kubernetes deployment to integration successful
- [x] Tag release

### Previewnet

v1 is deployed by tag creation automation. Deploy v2 soon after v1 is successful.

- [x] Deployed v1
- [x] Deployed v2

### Performance

- [x] Deployed v1
- [x] Deployed v2
- [x] gRPC API performance tests
- [x] Importer performance tests

### Mainnet Staging

- [x] Deployed v1
- [ ] Deployed v2
- [x] REST API performance tests
- [x] Web3 API performance tests

## Generally Available

- [x] Publish release
- [ ] Publish marketplace release

### Previewnet

v1 is deployed by tag creation automation. Deploy v2 soon after v1 is successful.

- [x] Deployed v1
- [x] Deployed v2

### Testnet

The GA tag automation deploys v1 to testnet-na. Upon success, deploy v1 and v2 to testnet-eu.

- [x] Deployed v1
- [x] Deployed v2

### Integration Docker

This preprod environment is automatically deployed for any GA release.

- [x] Deployed

### Dev

This preprod environment is automatically deployed for any GA release.

- [x] Deployed

### Staging Small

This environment does migration testing against testnet state. We should deploy GA versions to it after testnet is
successfully updated.

- [x] Deployed

### Mainnet

- [x] Deployed

### Staging Large

This environment does migration testing against mainnet state. We should deploy GA versions to it after mainnet is
successfully updated.

- [x] Deployed

## Post Release

- [x] Update any completed HIPs to its status to `Final` and populate the `release`.

**Comment by jascks** [comment]
Closing this issue with these comments:
1. 0.106 was not deployed to `mainnet-staging` v2 due to ongoing Citus/migration testing. 0.107 is out there now.
2. No releases can be published on GCP Marketplace due to a bug on their end. 0.107 is the current release now (and subject to the same bug).
