### ISSUE TITLE
Release Checklist 0.107

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#8518]
## Release Checklist

This checklist verifies a release is rolled out successfully.

## Preparation

- [x] Milestone created
- [x] Milestone field populated on relevant [issues](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aclosed+no%3Amilestone+sort%3Aupdated-desc)
- [x] Nothing open for [milestone](https://github.com/hashgraph/hedera-mirror-node/issues?q=is%3Aopen+sort%3Aupdated-desc+milestone%3A0.107.0)
- [x] GitHub checks for branch are passing
- [x] No pre-release or snapshot dependencies present in build files
- [x] Verify hedera-services protobuf dependency doesn't contain any unsupported fields
- [x] Automated Kubernetes deployment to integration successful
- [x] Tag release

### Previewnet

v1 is deployed by tag creation automation. Deploy v2 soon after v1 is successful.

- [x] Deployed v1
- [x] Deployed v2

### Performance

- [x] Deployed v1
- [x] Deployed v2
- [x] gRPC API performance tests
- [x] Importer performance tests

### Mainnet Staging

- [x] Deployed v1
- [x] Deployed v2
- [x] REST API performance tests
- [x] Web3 API performance tests

## Generally Available

- [x] Publish release
- [ ] Publish marketplace release

### Previewnet

v1 is deployed by tag creation automation. Deploy v2 soon after v1 is successful.

- [x] Deployed v1
- [x] Deployed v2

### Testnet

The GA tag automation deploys v1 to testnet-na. Upon success, deploy v1 and v2 to testnet-eu.

- [x] Deployed v1
- [x] Deployed v2

### Integration Docker

This preprod environment is automatically deployed for any GA release.

- [x] Deployed

### Dev

This preprod environment is automatically deployed for any GA release.

- [x] Deployed

### Staging Small

This environment does migration testing against testnet state. We should deploy GA versions to it after testnet is
successfully updated.

- [x] Deployed

### Mainnet

- [x] Deployed

### Staging Large

This environment does migration testing against mainnet state. We should deploy GA versions to it after mainnet is
successfully updated.

- [x] Deployed

## Post Release

- [x] Update any completed HIPs to its status to `Final` and populate the `release`.

**Comment by xin-hedera** [comment]
`Publish marketplace release` blocked due to error during validation, would need to contract google marketplace for more details.
